"use strict";

const assert = require("assert");
const fs = require("fs");

const read = (file) => fs.readFileSync(file, "utf8");
const chromeFeatures = read("extensions/chrome/features.js");
const firefoxFeatures = read("extensions/firefox/features.js");
const safariFeatures = read("extensions/safari/features.js");
const chromeContent = read("extensions/chrome/content.js");
const firefoxContent = read("extensions/firefox/content.js");
const safariContent = read("extensions/safari/content.js");
const chromePopup = read("extensions/chrome/popup.js");
const firefoxPopup = read("extensions/firefox/popup.js");
const chromeHtml = read("extensions/chrome/popup.html");
const firefoxHtml = read("extensions/firefox/popup.html");
const safariHtml = read("extensions/safari/popup.html");

assert.strictEqual(chromeFeatures, firefoxFeatures, "Chrome and Firefox feature normalization stays identical");
assert.strictEqual(chromeContent, firefoxContent, "Chrome and Firefox content scripts stay identical");
assert.strictEqual(chromeContent, safariContent, "Chrome and Safari content scripts stay identical");
assert.strictEqual(chromePopup, firefoxPopup, "Chrome and Firefox popup logic stays identical");
assert.strictEqual(chromeHtml, firefoxHtml, "Chrome and Firefox popup markup stays identical");
assert.match(chromeFeatures, /spacing:false/);
assert.match(chromeFeatures, /lineHeight:1\.5/);
assert.match(chromeFeatures, /letterSpacing:0\.03/);
assert.match(chromeFeatures, /wordSpacing:0\.2/);
assert.match(chromeFeatures, /out\.lineHeight = Math\.max\(1, Math\.min\(2\.2/);
assert.match(chromeFeatures, /out\.letterSpacing = Math\.max\(0, Math\.min\(0\.2/);
assert.match(chromeFeatures, /out\.wordSpacing = Math\.max\(0, Math\.min\(0\.8/);
assert.match(chromeContent, /nr-spacing-active/);
assert.match(chromeContent, /--nr-line-height/);
assert.match(chromeContent, /--nr-letter-spacing/);
assert.match(chromeContent, /--nr-word-spacing/);
assert.match(chromeContent, /:not\(input\):not\(textarea\):not\(select\):not\(option\)/);
assert.match(chromeContent, /:not\(\[contenteditable\]\)/);
assert.match(chromeContent, /role='slider'/);
assert.match(chromeContent, /nr-spacing-shadow-style/);
assert.match(chromePopup, /spacing: featureSettings\.spacing/);
assert.match(chromePopup, /lineHeight: featureSettings\.lineHeight/);
assert.match(chromePopup, /letterSpacing: featureSettings\.letterSpacing/);
assert.match(chromePopup, /wordSpacing: featureSettings\.wordSpacing/);
assert.match(chromeHtml, /data-setting="spacing"/);
assert.match(chromeHtml, /data-setting="lineHeight"/);
assert.match(chromeHtml, /data-setting="letterSpacing"/);
assert.match(chromeHtml, /data-setting="wordSpacing"/);
assert.match(safariHtml, /data-setting="spacing"/);
assert.match(read("extensions/safari/popup.js"), /function normalizeSettings/);
assert.match(read("extensions/safari/popup.js"), /NeuroReaderFeatures\.normalize/);
assert.match(read("extensions/safari/popup.js"), /featureSettings = normalizeSettings\(featureSettings\)/);
assert.ok(!chromeContent.includes("function transform("), "content script does not redefine the protected formula");

console.log("Phase 29 spacing tests passed.");
